"""add_opportunity_model

Revision ID: 7770543dc37d
Revises: f0c74d3d54f0
Create Date: 2026-05-22 10:25:19.121445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7770543dc37d'
down_revision: Union[str, None] = 'f0c74d3d54f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_tenant_id'), 'automation_rules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_automation_rules_trigger_event'), 'automation_rules', ['trigger_event'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('conditions_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('assignee_type', sa.String(length=50), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rules_tenant_id'), 'routing_rules', ['tenant_id'], unique=False)
    op.create_table('automation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('trigger_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions_executed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_logs_rule_id'), 'automation_logs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_automation_logs_tenant_id'), 'automation_logs', ['tenant_id'], unique=False)
    op.add_column('customers', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('recycle_count', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('recycle_history', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_device_trust_tenant_id'), 'device_trust', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('device_trust_user_id_fkey'), 'device_trust', type_='foreignkey')
    op.create_foreign_key(None, 'device_trust', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_refresh_tokens_tenant_id'), 'refresh_tokens', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_user_credentials_tenant_id'), 'user_credentials', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('user_credentials_user_id_fkey'), 'user_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'user_credentials', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_webauthn_challenges_tenant_id'), 'webauthn_challenges', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_challenges_tenant_id'), table_name='webauthn_challenges')
    op.drop_constraint(None, 'user_credentials', type_='foreignkey')
    op.create_foreign_key(op.f('user_credentials_user_id_fkey'), 'user_credentials', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_credentials_tenant_id'), table_name='user_credentials')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_refresh_tokens_tenant_id'), table_name='refresh_tokens')
    op.drop_constraint(None, 'device_trust', type_='foreignkey')
    op.create_foreign_key(op.f('device_trust_user_id_fkey'), 'device_trust', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_device_trust_tenant_id'), table_name='device_trust')
    op.drop_column('customers', 'recycle_history')
    op.drop_column('customers', 'recycle_count')
    op.drop_column('customers', 'assigned_at')
    op.drop_index(op.f('ix_automation_logs_tenant_id'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_rule_id'), table_name='automation_logs')
    op.drop_table('automation_logs')
    op.drop_index(op.f('ix_routing_rules_tenant_id'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_automation_rules_trigger_event'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_tenant_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###