#!/usr/bin/env python3
"""Validate open GitHub issues with Claude; mark valid ones as ready to implement.

For each open issue that hasn't already been triaged, ask Claude whether the
issue is well-defined enough to start implementing. If yes, add a "ready" label
and a "Ready to implement" comment. If no, add a "needs-clarification" label
and a comment explaining what information is missing.

Designed to be invoked from a scheduled GitHub Actions workflow. A per-run cap
(`MAX_ISSUES_PER_RUN`, default 5) keeps cost bounded.
"""

import json
import os
import re
import subprocess
import sys
from json import JSONDecoder
from typing import Any


LABEL_READY = "ready"
LABEL_NEEDS_INFO = "needs-clarification"
LABEL_AUTOMATED = "automated"
LABEL_BLOCKED = "blocked"
LABEL_SPLIT = "split"
# Issues with any of these labels are skipped — already triaged (ready /
# needs-clarification / split) or auto-generated by another pipeline that we
# shouldn't re-judge as a feature request. `blocked` is intentionally NOT
# here — we re-check those each tick so they auto-unblock once deps close.
SKIP_LABELS = {LABEL_READY, LABEL_NEEDS_INFO, LABEL_SPLIT, "doc-sync", "code-review", "pipeline"}
COMMENT_MARKER = "<!-- agent-job-issue-validator -->"
BLOCKED_COMMENT_MARKER = "<!-- agent-job-issue-validator:blocked -->"
# Target work budget. If implementing an issue would take longer than this,
# the validator asks Claude to break it into subtasks instead of marking it
# ready. Tune via the IMPLEMENTATION_BUDGET_MINUTES env var on the workflow.
DEFAULT_BUDGET_MINUTES = 30
# Matches "Depends on #123", "Blocked by #123", with optional colon. Same-repo
# only; cross-repo refs like owner/repo#123 are intentionally ignored to keep
# the dependency check scoped to issues this script can actually inspect.
DEP_PATTERN = re.compile(r"(?i)(?:depends on|blocked by)\s*:?\s*#(\d+)")


def log(msg: str) -> None:
    print(f"[issue-monitor] {msg}", flush=True)


def run_gh(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["gh", *args], capture_output=True, text=True, check=False)


def list_open_issues() -> list[dict[str, Any]]:
    """Return open issues (gh issue list excludes PRs by default)."""
    result = run_gh(
        [
            "issue", "list",
            "--state", "open",
            "--json", "number,title,body,labels",
            "--limit", "100",
        ]
    )
    if result.returncode != 0:
        log(f"list_failed rc={result.returncode} stderr={result.stderr.strip()}")
        return []
    try:
        return json.loads(result.stdout or "[]")
    except json.JSONDecodeError:
        return []


def has_any_label(issue: dict[str, Any], names: set[str]) -> bool:
    return any((lbl.get("name") or "") in names for lbl in (issue.get("labels") or []))


def ensure_labels() -> None:
    for lbl in (LABEL_READY, LABEL_NEEDS_INFO, LABEL_AUTOMATED, LABEL_BLOCKED, LABEL_SPLIT):
        run_gh(["label", "create", lbl, "--force"])


def budget_minutes() -> int:
    raw = os.environ.get("IMPLEMENTATION_BUDGET_MINUTES")
    if not raw:
        return DEFAULT_BUDGET_MINUTES
    try:
        return max(5, int(raw))
    except ValueError:
        return DEFAULT_BUDGET_MINUTES


def parse_dependencies(body: str | None) -> list[int]:
    """Return same-repo issue numbers mentioned as 'Depends on #N' / 'Blocked by #N'."""
    if not body:
        return []
    seen: set[int] = set()
    out: list[int] = []
    for m in DEP_PATTERN.finditer(body):
        n = int(m.group(1))
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def fetch_issue_state(number: int) -> str | None:
    """Return 'OPEN' / 'CLOSED' for an issue, or None if the lookup fails."""
    r = run_gh(["issue", "view", str(number), "--json", "state"])
    if r.returncode != 0:
        return None
    try:
        return (json.loads(r.stdout or "{}").get("state") or "").upper() or None
    except json.JSONDecodeError:
        return None


def open_blockers(deps: list[int]) -> list[int]:
    """Subset of deps that aren't closed. Unknown state counts as blocking — safer to
    wait for human inspection than to greenlight a 'ready' on a broken reference."""
    blockers: list[int] = []
    for n in deps:
        state = fetch_issue_state(n)
        if state != "CLOSED":
            blockers.append(n)
    return blockers


def build_prompt(issue: dict[str, Any], budget: int) -> str:
    title = issue.get("title") or "(no title)"
    body = (issue.get("body") or "(no body)").strip()
    return f"""You are triaging a GitHub issue and deciding what should happen to it.

Title: {title}

Body:
{body}

Pick ONE of three verdicts:

1. "ready" — the issue is well-defined AND can be implemented end-to-end
   (including tests) in {budget} minutes or less by an experienced engineer
   following a clear plan.

2. "needs_clarification" — the issue is too vague, missing context, or
   asks a question rather than requesting a concrete change. List what
   information is needed before it could be picked up.

3. "too_large" — the issue is clear enough to act on, but implementing it
   would take MORE than {budget} minutes. Break it down into 2–5 smaller
   subtasks. Each subtask must independently fit the {budget}-minute budget.

What fits in {budget} minutes? Rough heuristic:
- Touches 1–3 source files plus 1–2 test files.
- Roughly 50–200 lines of code change in total.
- No simultaneous frontend AND backend changes (split them).
- No DB migration larger than a single column add / drop / type change.
- No "build a whole new feature with UI, API, and DB schema" — that's at
  minimum three subtasks.

Examples of "too_large":
- "Add a chat feature with sessions, messages, AI integration, frontend UI"
  → subtasks: schema + model, service, router, frontend store, frontend page.
- "Migrate authentication to OAuth2 across the app" → many subtasks.
- "Refactor the reporting subsystem" → must be scoped concretely.

Examples of "ready":
- "Add `is_active: bool` to UserModel and surface in the admin endpoint."
- "Fix off-by-one in tests/integration/test_billing.py::test_invoice_dates."
- "Reject empty email in CustomerService.create with ValidationException 422."

Respond with JSON only, no prose, no markdown fence. Use literal values:
{{
  "verdict": "ready" | "needs_clarification" | "too_large",
  "reason": "<one short sentence justifying the decision>",
  "missing": ["<only when needs_clarification — specific info still needed>"],
  "subtasks": [
    {{
      "title": "<short imperative title, e.g. 'Add chat_session ORM model and migration'>",
      "body": "<2–6 sentences: what to do, which files to touch, what acceptance looks like — scoped so it fits the {budget}-minute budget>"
    }}
  ]
}}

Rules for "subtasks":
- Only populate when verdict is "too_large". Empty list otherwise.
- Order matters: list them in implementation order (dependencies first).
- Each subtask body should be self-contained — another agent will read it
  standalone and produce a plan from it.
- Do not invent scope the parent didn't imply.
"""


def extract_json(text: str) -> dict[str, Any] | None:
    """Pull a JSON object out of Claude's output (possibly wrapped in --output-format json)."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        data = None

    if isinstance(data, dict):
        # Claude Code wrapper: {type:"result", result:"<inner JSON string>"}
        inner = data.get("result")
        if isinstance(inner, str):
            nested = extract_json(inner)
            if nested is not None:
                return nested
        return data

    decoder = JSONDecoder()
    for idx, char in enumerate(text):
        if char != "{":
            continue
        try:
            obj, _ = decoder.raw_decode(text[idx:])
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict):
            return obj
    return None


def call_claude(prompt: str) -> tuple[dict[str, Any] | None, str]:
    model = os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-6")
    timeout = int(os.environ.get("CLAUDE_TIMEOUT_SECONDS", "300"))
    max_attempts = max(1, int(os.environ.get("CLAUDE_MAX_ATTEMPTS", "2")))
    cmd = [
        "claude",
        "-p",
        "--model", model,
        "--max-turns", "15",
        "--output-format", "json",
    ]

    last_err = ""
    for attempt in range(1, max_attempts + 1):
        try:
            result = subprocess.run(
                cmd,
                input=prompt,
                capture_output=True,
                text=True,
                check=False,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            return None, "claude_timed_out"
        except OSError as e:
            return None, f"claude_not_runnable: {e}"

        if result.returncode != 0:
            stdout_tail = (result.stdout or "").strip()[-300:]
            stderr_tail = (result.stderr or "").strip()[-200:]
            last_err = (
                f"claude_rc={result.returncode} stderr={stderr_tail!r} "
                f"stdout_tail={stdout_tail!r}"
            )
        else:
            parsed = extract_json(result.stdout or "")
            # Accept new "verdict" schema, plus the old "valid" schema for
            # one tick's worth of backwards compat (in case a run was already
            # in flight when the prompt was rolled out).
            if isinstance(parsed, dict) and ("verdict" in parsed or "valid" in parsed):
                return parsed, ""
            stdout_head = (result.stdout or "").strip()[:300]
            last_err = f"parse_failed stdout_head={stdout_head!r}"

        if attempt < max_attempts:
            log(f"claude_retry attempt={attempt}/{max_attempts} err={last_err}")

    return None, last_err


def comment_and_label(number: int, body: str, label: str) -> bool:
    # Apply the skip-label BEFORE commenting. If the label step fails (rate
    # limit, transient error), we abort without commenting — that way the next
    # cron tick retries cleanly instead of piling another duplicate comment
    # onto an issue that still doesn't have the skip-label set.
    l = run_gh(["issue", "edit", str(number), "--add-label", label])
    if l.returncode != 0:
        log(f"label_failed issue=#{number} label={label} stderr={l.stderr.strip()}")
        return False

    comment_body = f"{COMMENT_MARKER}\n{body}"
    c = run_gh(["issue", "comment", str(number), "--body", comment_body])
    if c.returncode != 0:
        log(f"comment_failed issue=#{number} stderr={c.stderr.strip()}")
        return False
    return True


def create_subtasks(parent_number: int, subtasks: list[dict[str, Any]]) -> list[int]:
    """Create each subtask as a fresh GitHub issue and return the new numbers.

    Each subtask body gets a "Subtask of #N" reference so GitHub renders the
    parent/child relation automatically. Subtasks are linked in a linear
    "Depends on #<prev>" chain so the dependency check in process_issue keeps
    later subtasks `blocked` until the earlier ones close — Claude is asked
    to emit them in implementation order, so the chain matches that order.
    We deliberately do NOT pre-label the children as `ready` — the next
    monitor-issues tick will re-validate them and either ready them or flag
    them, providing a sanity check on the splitter's output.
    """
    created: list[int] = []
    for i, st in enumerate(subtasks, 1):
        title = (st.get("title") or "").strip()
        body = (st.get("body") or "").strip()
        if not title:
            log(f"subtask_skipped parent=#{parent_number} index={i} reason=empty_title")
            continue
        header_lines = [f"Subtask of #{parent_number}"]
        if created:
            header_lines.append(f"Depends on #{created[-1]}")
        full_body = "\n".join(header_lines) + f"\n\n{body}"
        # Use --body-file - on stdin so long bodies don't hit ARG_MAX.
        r = subprocess.run(
            ["gh", "issue", "create", "--title", title, "--body-file", "-"],
            input=full_body,
            capture_output=True,
            text=True,
            check=False,
        )
        if r.returncode != 0:
            log(f"subtask_create_failed parent=#{parent_number} title={title!r} stderr={r.stderr.strip()[:200]}")
            continue
        # gh issue create prints the issue URL on success
        url = (r.stdout or "").strip()
        # Extract the issue number from the trailing /issues/<N> segment.
        try:
            new_number = int(url.rsplit("/", 1)[-1])
        except ValueError:
            log(f"subtask_create_url_parse_failed parent=#{parent_number} url={url!r}")
            continue
        created.append(new_number)
        log(f"subtask_created parent=#{parent_number} new=#{new_number} url={url}")
    return created


def process_issue(issue: dict[str, Any]) -> bool:
    number = issue["number"]
    title = issue.get("title") or ""
    log(f"validating issue=#{number} title={title!r}")

    deps = parse_dependencies(issue.get("body"))
    was_blocked = has_any_label(issue, {LABEL_BLOCKED})
    if deps:
        blockers = open_blockers(deps)
        if blockers:
            # Idempotent: --add-label is a no-op if already present. We only
            # post a comment on the transition (not yet labelled blocked), so
            # repeated cron ticks don't pile duplicates onto the same issue.
            run_gh(["issue", "edit", str(number), "--add-label", LABEL_BLOCKED])
            if not was_blocked:
                body = (
                    f"{BLOCKED_COMMENT_MARKER}\n**Blocked — waiting on:** "
                    + ", ".join(f"#{n}" for n in blockers)
                )
                run_gh(["issue", "comment", str(number), "--body", body])
                log(f"marked_blocked issue=#{number} open_deps={blockers}")
            else:
                log(f"still_blocked issue=#{number} open_deps={blockers}")
            return False
        if was_blocked:
            # All deps closed — drop the label and fall through to Claude.
            run_gh(["issue", "edit", str(number), "--remove-label", LABEL_BLOCKED])
            log(f"unblocked issue=#{number}")

    budget = budget_minutes()
    parsed, err = call_claude(build_prompt(issue, budget))
    if err:
        log(f"skip issue=#{number} err={err}")
        return False

    # Verdict resolution: prefer the new "verdict" field; fall back to the
    # legacy "valid" boolean for any in-flight runs from before this prompt
    # rolled out.
    raw_verdict = (parsed.get("verdict") or "").strip().lower()
    if not raw_verdict:
        raw_verdict = "ready" if bool(parsed.get("valid")) else "needs_clarification"

    reason = (parsed.get("reason") or "").strip()
    missing = parsed.get("missing") or []
    if not isinstance(missing, list):
        missing = [str(missing)]
    subtasks = parsed.get("subtasks") or []
    if not isinstance(subtasks, list):
        subtasks = []
    subtasks = [s for s in subtasks if isinstance(s, dict)]

    if raw_verdict == "ready":
        body = "**Ready to implement** ✅"
        if reason:
            body += f"\n\n{reason}"
        ok = comment_and_label(number, body, LABEL_READY)
        log(f"marked_ready issue=#{number} ok={ok}")
        return True

    if raw_verdict == "too_large":
        if len(subtasks) < 2:
            # Claude said "too large" but gave us no actionable split — fall
            # back to needs-clarification so a human can intervene rather
            # than leaving the issue stuck without progress.
            log(f"too_large_but_no_subtasks issue=#{number} — falling back to needs_clarification")
            body = (
                "**Needs clarification** ⚠️\n\n"
                + (reason or "Estimated to exceed the implementation budget, but no actionable split was produced.")
                + f"\n\nBudget: {budget} min."
            )
            ok = comment_and_label(number, body, LABEL_NEEDS_INFO)
            log(f"marked_needs_info issue=#{number} ok={ok} fallback_from=too_large")
            return True

        created = create_subtasks(number, subtasks)
        if not created:
            log(f"split_failed issue=#{number} — no subtasks created; not labelling, will retry next tick")
            return False

        lines = [
            f"**Split into {len(created)} subtask{'s' if len(created) != 1 else ''}** 🪓",
            "",
            reason or f"Estimated to exceed the {budget}-minute budget; split into smaller pieces.",
            "",
            "**Subtasks:**",
        ]
        lines.extend(f"- #{n}" for n in created)
        lines.append("")
        lines.append("_The original issue stays open as the tracking parent. Subtasks will be re-validated on the next monitor tick and picked up independently._")
        ok = comment_and_label(number, "\n".join(lines), LABEL_SPLIT)
        log(f"marked_split issue=#{number} subtasks={created} ok={ok}")
        return True

    # Anything else (including explicit "needs_clarification") → needs_info
    lines = ["**Needs clarification** ⚠️"]
    if reason:
        lines.append("")
        lines.append(reason)
    if missing:
        lines.append("")
        lines.append("**Missing:**")
        lines.extend(f"- {m}" for m in missing if isinstance(m, str) and m.strip())
    ok = comment_and_label(number, "\n".join(lines), LABEL_NEEDS_INFO)
    log(f"marked_needs_info issue=#{number} ok={ok}")
    return True


def main() -> int:
    ensure_labels()

    issues = list_open_issues()
    log(f"open_issues_total={len(issues)}")

    candidates = [i for i in issues if not has_any_label(i, SKIP_LABELS)]
    log(f"candidates_after_filter={len(candidates)} skip_labels={sorted(SKIP_LABELS)}")

    if not candidates:
        log("nothing_to_do")
        return 0

    max_per_run = int(os.environ.get("MAX_ISSUES_PER_RUN", "5"))
    processed = 0
    for issue in candidates[:max_per_run]:
        if process_issue(issue):
            processed += 1

    log(f"done processed={processed} cap={max_per_run} remaining={max(0, len(candidates) - max_per_run)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
